llava:
  model: "Intel/llava-gemma-2b"

dataset:
  json_path: "~/datasets/ReasonSeg/explanatory/train.json"
  image_dir: "~/datasets/ReasonSeg/train"
  mask_dir: "~/datasets/ReasonSeg/masks"

sam:
  model: "vit_b"
  checkpoint_dir: "~/models/SAM"
  resize: 1024
  n_masks: 20