llava:
  model: "Intel/llava-gemma-2b"

dataset:
  json_path: "..."
  image_dir: "..."
  mask_dir: "..."

sam:
  model: "vit_b"
  checkpoint_dir: "..."
  resize: 1024
  n_masks: 20

alphaclip:
  model: "ViT-B/16"
  checkpoint_dir: "..."

others:
  wandb_token: "TOKEN"